version: 2
project_name: refract

before:
  hooks:
    - go mod tidy

snapshot:
  version_template: "{{ .Tag }}"

checksum:
  name_template: "checksums.txt"

builds:
  - id: refract-build
    binary: refract
    main: ./cmd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X refract.BuildCommit={{ .Commit }}
      - -X refract.BuildDate={{ .Date }}

archives:
  - id: refract-archive
    formats: [ "tar.gz" ]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - refract.service
      - .service-env.default

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .Env.GITHUB_REPOSITORY_NAME }}"
  draft: true
  prerelease: auto

nfpms:
  - id: refract-pkg
    package_name: refract
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    maintainer: "quyxishi <874contact@proton.me>"
    description: "A policy enforcement service that provides real-time session concurrency control for Xray-core"
    homepage: https://github.com/quyxishi/refract
    license: MIT
    formats: [deb, rpm]
    bindir: /opt/refract
    contents:
      - src: .service-env.default
        dst: /etc/default/refract
        type: config|noreplace
      - src: refract.service
        dst: /etc/systemd/system/refract.service
        type: config
    scripts:
      postinstall: ./scripts/postinstall.sh
      preremove: ./scripts/preremove.sh
      postremove: ./scripts/postremove.sh

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"